Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,22 +27,22 @@ jobs:
       # Step 3: Copy the application code to the correct directory on the server using rsync
       - name: Copy files to the server
         run: |
-          ssh -o StrictHostKeyChecking=no root@203.161.38.194 'mkdir -p /home/fastapi/Lms-backend-api'
-          rsync -avz --exclude '.git' --exclude 'node_modules' ./ root@203.161.38.194:/home/fastapi/Lms-backend-api/
+          ssh -o StrictHostKeyChecking=no root@203.161.38.194 'mkdir -p /home/fastapi/lms-backend'
+          rsync -avz --exclude '.git' --exclude 'node_modules' ./ root@203.161.38.194:/home/fastapi/lms-backend/
 
       # Step 4: SSH into the server and deploy the updated application
-      # - name: Deploy the application
-      #   run: |
-      #     ssh -o StrictHostKeyChecking=no root@203.161.38.194 << 'EOF'
-      #       cd /home/fastapi/lms-backend-api
-      #       # sudo docker-compose -f docker-compose.yml down
-      #       sudo docker-compose -f docker-compose-dev.yml up --build -d
-      #       sudo docker image prune
-      #       # General error log check (you can customize or expand these patterns)
-      #       ERROR_LOG=$(sudo docker-compose logs web | grep -E -i 'error|exception|traceback|undefinedtable|fail|fatal')
-      #       if [[ -n "$ERROR_LOG" ]]; then
-      #         echo "Critical error found in web_1 logs:"
-      #         echo "$ERROR_LOG"
-      #         exit 1  # Fail the deployment if any error is found
-      #       fi
-      #     EOF
+      - name: Deploy the application
+        run: |
+          ssh -o StrictHostKeyChecking=no root@203.161.38.194 << 'EOF'
+            cd /home/fastapi/lms-backend
+            # sudo docker-compose -f docker-compose.yml down
+            sudo docker-compose -f docker-compose-dev.yml up --build -d
+            sudo docker image prune -f
+            # General error log check (you can customize or expand these patterns)
+            ERROR_LOG=$(sudo docker-compose logs web | grep -E -i 'error|exception|traceback|undefinedtable|fail|fatal')
+            if [[ -n "$ERROR_LOG" ]]; then
+              echo "Critical error found in web_1 logs:"
+              echo "$ERROR_LOG"
+              exit 1  # Fail the deployment if any error is found
+            fi
+          EOF
